#!/bin/bash
#SBATCH --qos highmem1
#SBATCH --account=iacc_jeirinlo
#SBATCH --partition IB_44C_512G

# Number of nodes
#SBATCH -N 1

# Number of tasks
#SBATCH -n 8

#SBATCH --output=log_RMasker

##########################################################
# Setup envrionmental variable. 
##########################################################
export OMP_NUM_THREADS=$SLURM_CPUS_ON_NODE
. $MODULESHOME/../global/profile.modules
module load RepeatMasker-4.1.0
pwd; hostname; date
 
echo "Running program on $SLURM_CPUS_ON_NODE CPU cores"

##########################################################

# FastA URL
fasta="/scratch/jeirinlo/jrodr979/Halophila_WGBS_Dec2023/Halophila_genome_2020_publication/halophila_stipulacea_illumina_genome.fasta"

# Run RepeatMasker

echo ""
echo "Running RepeatMasker. This may take awhile."
echo ""
RepeatMasker \
"${fasta}" \
-species "all" \
-par 8 \
-gff \
-excln \
1> stdout.txt \
2> stderr.txt
echo "All done! Check stderr.txt for any problems."
